export const BUILT_IN_RECIPES = [
  { code: "Z/V1", title: "Overnight oats", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V2", title: "Tortilja s piščancem", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V3", title: "Jajca s kruhom in avokadom", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V4", title: "Tunin sendvič", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V5", title: "Solata s tuno in jajcem", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V6", title: "Tortilja s tuno in avokadom", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V7", title: "Ameriške palačinke z grškim jogurtom", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V8", title: "Šmorn z grškim jogurtom", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V9", title: "Grški jogurt s sadjem", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "Z/V10", title: "Dimljen losos na kruhu", meal_type: "zajtrk-vecerja", source: "built-in" },
  { code: "K1", title: "Bolognese", meal_type: "kosilo", source: "built-in" },
  { code: "K2", title: "Pečen piščanec s krompirjem in zelenjavo", meal_type: "kosilo", source: "built-in" },
  { code: "K3", title: "Krompirjeva solata z jajci", meal_type: "kosilo", source: "built-in" },
  { code: "K4", title: "Puranji trakovi z rižem in zelenjavo", meal_type: "kosilo", source: "built-in" },
  { code: "K5", title: "Tuna mehiška solata", meal_type: "kosilo", source: "built-in" },
  { code: "K6", title: "Azijski piščanec z rižem in indijskimi oreščki", meal_type: "kosilo", source: "built-in" },
  { code: "K7", title: "Piščanec s čičerikinimi testeninami v kremni omaki", meal_type: "kosilo", source: "built-in" },
  { code: "K8", title: "Bolonjez z bešamelom iz grškega jogurta", meal_type: "kosilo", source: "built-in" },
  { code: "K9", title: "BBQ piščanec s sladkim krompirjem", meal_type: "kosilo", source: "built-in" },
  { code: "K10", title: "Riba na žaru s krompirjem in blitvo", meal_type: "kosilo", source: "built-in" },
  { code: "K11", title: "Testenine s tuno", meal_type: "kosilo", source: "built-in" },
  { code: "K12", title: "Losos bowl z rižem in zelenjavo", meal_type: "kosilo", source: "built-in" },
  { code: "K13", title: "Losos s testeninami", meal_type: "kosilo", source: "built-in" },
];

export const BUILT_IN_CODES = new Set(BUILT_IN_RECIPES.map((recipe) => recipe.code));
